from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List
import argparse
import os
import sys
import uuid

try:
    import commentjson as json
except ImportError:
    sys.stderr.write(
        "Error: commentjson is not installed. Please run "
        "'pip install commentjson' to install it.\n"
    )
    try:
        import json  # type: ignore[no-redef]
    except ImportError:
        sys.stderr.write("Error: json is not available. Cannot continue.\n")
        sys.exit(1)


@dataclass
class VSCodeConfigUpdater:
    workspace_folder: Path
    python_module_dirs: List[Path] = field(default_factory=list)

    def __post_init__(self):
        # Build PYTHONPATH roots from discovered module directories.
        self.python_paths = [os.path.sep.join(p.parts[:-1]) for p in self.python_module_dirs]
        self.python_separator_paths = [
            "${pathSeparator}".join(p.parts[:-1]) for p in self.python_module_dirs
        ]
        self.unix_slash_paths = [p.replace("\\", "/") for p in self.python_paths]

    def _load_json(self, file_path: Path) -> Dict:
        if file_path.exists():
            with file_path.open("r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    def _safe_write_text(self, file_path: Path, content: str):
        file_path.parent.mkdir(parents=True, exist_ok=True)
        temp_file = file_path.with_suffix(f".{uuid.uuid4().hex}.tmp")
        try:
            temp_file.write_text(content, encoding="utf-8")
            temp_file.replace(file_path)
        finally:
            if temp_file.exists():
                temp_file.unlink()

    def _save_json(self, file_path: Path, data: Dict):
        json_content = json.dumps(data, indent=4)
        self._safe_write_text(file_path, json_content)

    def update_env_file(self, env_file: Path, args: argparse.Namespace):
        add_pythonpath = args.add_pythonpath
        add_env = args.add_env

        if not add_env:
            if env_file.exists():
                env_file.unlink()
            return

        workspace_str = self.workspace_folder
        os_sep = os.path.sep
        pythonpath = ";".join(f"${{WORKSPACE_FOLDER}}{os_sep}{p}" for p in self.python_paths)
        ppsuffix = ";${PYTHONPATH}" if add_pythonpath else ""

        env_content = (
            f"WORKSPACE_FOLDER={workspace_str}\n"
            f"PYTHONPATH={pythonpath}{ppsuffix}\n"
        )
        self._safe_write_text(env_file, env_content)

    def update_local_settings_py(self, local_settings_file: Path, _args: argparse.Namespace):
        os_sep = os.path.sep
        path_sep = ":" if os.sep == "/" else ";"
        workspace_str = self.workspace_folder
        abs_paths = [f"{{WORKSPACE}}{os_sep}{p}" for p in self.python_paths]
        pythonpath = f"\n    {path_sep!r} ".join(f"f{p!r}" for p in abs_paths)

        this_file = Path(__file__).relative_to(self.workspace_folder)

        local_settings_content = (
            f"# This file is automatically generated by {this_file}\n"
            f"from pathlib import Path\n"
            f"WORKSPACE = {str(workspace_str)!r} if Path.cwd().parts[-1] != 'grip-dev' else str(Path.cwd())\n"
            f"PYTHONPATH = (\n    {pythonpath}\n)\n"
            "if __name__ == '__main__':\n"
            "    print(PYTHONPATH)\n"
        )

        self._safe_write_text(local_settings_file, local_settings_content)

    def update_settings(self, settings_file: Path, args: argparse.Namespace):
        add_env = args.add_env
        add_pythonpath = args.add_pythonpath
        settings = self._load_json(settings_file)

        paths = [str(p).replace("\\", "/") for p in self.python_separator_paths]
        win_paths = ";".join(f"${{workspaceFolder}}${{pathSeparator}}{p}" for p in paths)
        unix_paths = ":".join(f"${{workspaceFolder}}${{pathSeparator}}{p}" for p in paths)

        settings["python.analysis.extraPaths"] = [
            f"${{workspaceFolder}}/{p}" for p in self.unix_slash_paths
        ]

        ppsuffix = ";${env:PYTHONPATH}" if add_pythonpath else ""
        settings.setdefault("terminal.integrated.env.windows", {})["PYTHONPATH"] = (
            f"{win_paths}{ppsuffix}"
        )
        settings.setdefault("terminal.integrated.env.linux", {})["PYTHONPATH"] = (
            f"{unix_paths}{ppsuffix}"
        )
        settings.setdefault("terminal.integrated.env.osx", {})["PYTHONPATH"] = (
            f"{unix_paths}{ppsuffix}"
        )

        if add_env:
            settings["python.envFile"] = "${workspaceFolder}/.vscode/.env"
        elif "python.envFile" in settings:
            del settings["python.envFile"]

        self._save_json(settings_file, settings)

    def update_launch(self, launch_file: Path, args: argparse.Namespace):
        add_pythonpath = args.add_pythonpath
        launch_config = self._load_json(launch_file)
        if not launch_config:
            launch_config = {"version": "0.2.0", "configurations": []}

        paths = [str(p).replace("\\", "/") for p in self.python_separator_paths]
        win_paths = ";".join(f"${{workspaceFolder}}${{pathSeparator}}{p}" for p in paths)
        ppsuffix = ";${env:PYTHONPATH}" if add_pythonpath else ""

        python_config = None
        for config in launch_config.get("configurations", []):
            if config.get("name") == "Python: Current File":
                python_config = config
                break

        if not python_config:
            python_config = {
                "name": "Grip: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "cwd": "${fileDirname}",
                "console": "integratedTerminal",
                "justMyCode": False,
            }
            launch_config.setdefault("configurations", []).append(python_config)

        python_config.setdefault("env", {})["PYTHONPATH"] = f"{win_paths}{ppsuffix}"
        self._save_json(launch_file, launch_config)

    @classmethod
    def relationships(cls):
        return {
            ".env": cls.update_env_file,
            "settings.json": cls.update_settings,
            "launch.json": cls.update_launch,
            "local_settings.py": cls.update_local_settings_py,
        }


def find_src_modules(root_dir: Path) -> List[Path]:
    src_paths = set()

    for path in root_dir.rglob("src/*/__init__.py"):
        if "tests" in path.parts:
            continue
        src_paths.add(path.parent.relative_to(root_dir))

    for path in root_dir.rglob("src/*/*/__init__.py"):
        if "tests" in path.parts:
            continue
        rel_path = path.parent.relative_to(root_dir)
        src_paths.add(Path(rel_path.parts[0]) / rel_path.parts[1] / rel_path.parts[2])

    return sorted(list(src_paths))


def update_vscode_configs(args: argparse.Namespace):
    workspace_root = args.workspace_root.resolve()
    src_paths = find_src_modules(workspace_root)

    vscode_dir = workspace_root / ".vscode"
    vscode_dir.mkdir(exist_ok=True)

    updater = VSCodeConfigUpdater(workspace_root, src_paths)
    for file_name, func in VSCodeConfigUpdater.relationships().items():
        func(updater, vscode_dir / file_name, args)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update VS Code configuration files for Python projects"
    )
    parser.add_argument(
        "--workspace-root",
        type=Path,
        default=Path.cwd(),
        help="Root directory of the workspace (default: current directory)",
    )
    parser.add_argument(
        "--create",
        type=bool,
        default=True,
        help="Create missing .vscode files if they do not exist",
    )
    parser.add_argument(
        "--add_pythonpath",
        type=bool,
        default=(os.environ.get("PYTHONPATH", None) is not None),
        help="Append existing PYTHONPATH",
    )
    parser.add_argument(
        "--add_env",
        dest="add_env",
        action="store_true",
        help="Create/update .vscode/.env",
    )
    parser.add_argument(
        "--no-add_env",
        dest="add_env",
        action="store_false",
        help="Do not manage .vscode/.env",
    )
    parser.set_defaults(add_env=None)

    args = parser.parse_args()

    env_file = args.workspace_root / ".vscode" / ".env"
    if args.add_env is None:
        args.add_env = env_file.exists()

    if not args.create:
        for file_name in VSCodeConfigUpdater.relationships().keys():
            candidate = args.workspace_root / ".vscode" / file_name
            if not candidate.exists():
                print(
                    "Error: Wrong workspace root directory? The specified workspace "
                    f"root directory does not contain '{file_name}'. "
                    f"workspace root: '{args.workspace_root}'",
                    file=sys.stderr,
                )
                return 1

    update_vscode_configs(args)
    print(f"Successfully updated VS Code configs in {args.workspace_root / '.vscode'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

