# This file is automatically generated by dev-setup/src/vscode_configutator/vscode_configutator.py
from pathlib import Path
WORKSPACE = '/Users/owebeeone/limbo/grip-dev' if Path.cwd().parts[-1] != 'grip-dev' else str(Path.cwd())
PYTHONPATH = (
    f'{WORKSPACE}/grip-py/src'
)
if __name__ == '__main__':
    print(PYTHONPATH)
